jwt:
  authorities:
    key: roles
  header:
    string: Authorization
  signing:
    key: signingkey
  token:
    prefix: Bearer
    validity: 18000

server:
  port: 8081

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5429/postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: true