jwt:
  authorities:
    key: roles
  header:
    string: Authorization
  signing:
    key: signingkey
  token:
    prefix: Bearer
    validity: 18000

server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:file:~/pz-social
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update